GH-blackwidow/graceshopper-project

- server/db/models/associations.js
- server/db/models/users.js
> User associations added

- package-lock.json
- package.json
- server/db/models/orders.js
- testspecs/db/order.spec.js
> feat: (model): created orders model

- server/db/models/users.js
> feat:(user): updated salting for password

- server/db/models/users.js
> updating version

- server/db/models/user.js
> feat: deployment

- server/api/products.js
> Product route

- client/components/AllProducts.js
- client/components/index.js
- client/components/navbar.js
- client/routes.js
- client/store/Products.js
- client/store/index.js
- client/store/store.js
> FE:updated allProducts components

- server/db/models/product.js
- server/db/models/user.js
- server/utils/adminsOnly.js
> Feat: Models slightly revised

- server/api/products.js
> fix(products):updated reference

- package-lock.json
- script/seed.js
- server/db/models/index.js
- server/db/models/order-products.js
> Feat: OrderProducts model, seed for database

- testspecs/orderProducts.spec.js
> TestSpecs: for OrderProducts Model

- server/db/models/user.js
- server/index.js
> FE: login and sign up

- server/api/cart.js
- server/api/index.js
- server/api/orders.js
updated routes for orders and cart
> feat: (orders and cart): gets past order and cart. Updates cart

- client/store/Cart.js
- client/store/Order.js
- client/store/store.js
- server/api/cart.js
- server/api/orders.js
[] Updated Cart & Order reducer and added to combine reducers
[] Updated back-end routes to better work with thunks
> fix: (reducers, routes): updates cart and order state and data

- server/api/cart.js
> Feat(cart):add route updates the cart quantity

- client/store/Products.js
> Product Thunks/Store added for adding and deleting products

- client/store/Products.js
> took out console.logs

- client/routes.js
> fix: (route):updated checkout

- client/store/Cart.js
> fix: cart added add and delete reducers

- client/components/AllProducts.js
- client/components/navbar.js
- public/index.html
- public/style.css
> added styling

- client/components/Checkout.js
- client/routes.js
- script/seed.js
- server/api/cart.js
> fix(checkout):update checkout
